# Generated by Django 4.0.4 on 2022-04-23 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_remove_comment_advert_delete_advert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='performer',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Performer must be greater than 2 characters')]),
        ),
    ]
