# Generated by Django 4.0.4 on 2022-04-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='showdate',
        ),
        migrations.AddField(
            model_name='event',
            name='showtime',
            field=models.TimeField(null=True),
        ),
    ]
