# Generated by Django 4.0.4 on 2022-04-24 04:41

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_date_event_showdate_event_showtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='showdate',
            field=models.DateField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date.today)]),
        ),
    ]
